stages:
  - build

transmute_build:
  stage: build
  tags:
    - bionicbeaver
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - bash .ci/linux_before_install.sh
    - mkdir /home/travis
    - useradd travis
    - chown travis. /home/travis
    - sudo -u travis bash -l -c "echo PATH=$HOME/.transmute/bin:$PATH >> $HOME/.bashrc"
    - sudo -u travis bash -l -c "echo PATH=$HOME/.local/bin:$PATH >> $HOME/.bashrc"
    - rm -Rf $HOME/.transmute
    - sudo -u travis bash -l .ci/ci.sh
