stages:
  - build
  - clean

transmute_build_osx:
  stage: build
  tags:
    - osx-shell
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - sudo rm -Rf $HOME/builds
    - sudo bash -c "echo PATH=$HOME/.transmute/bin:$PATH >> $HOME/.bashrc" - $USER
    - sudo bash -c "echo PATH=$HOME/.local/bin:$PATH >> $HOME/.bashrc" - $USER
    - TRAVIS_OS_NAME=osx PWD=$(pwd) sudo bash -c "cd $PWD; bash -l .ci/ci.sh" - $USER

transmute_clean_osx:
  stage: clean
  tags:
    - osx-shell
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - minikube delete
    - rm -Rf $HOME/.transmute
    - rm -Rf $HOME/.kube

transmute_build_virtualbox:
  stage: build
  tags:
    - bionicbeaver
    - virtualbox
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - su -c "echo PATH=/home/travis/.transmute/bin:$PATH >> /home/travis/.bashrc" - travis
    - su -c "echo PATH=/home/travis/.local/bin:$PATH >> /home/travis/.bashrc" - travis
    - rm -Rf /home/travis/.transmute
    - TRAVIS_OS_NAME=linux PWD=$(pwd) su -c "cd $PWD; bash -l .ci/ci.sh" - travis

transmute_clean_virtualbox:
  stage: clean
  tags:
    - bionicbeaver
    - virtualbox
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - echo clean

transmute_build_docker:
  stage: build
  tags:
    - bionicbeaver
    - docker
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - su -c "echo PATH=/home/travis/.transmute/bin:$PATH >> /home/travis/.bashrc" - travis
    - su -c "echo PATH=/home/travis/.local/bin:$PATH >> /home/travis/.bashrc" - travis
    - rm -Rf /home/travis/.transmute
    - TRAVIS_OS_NAME=linux PWD=$(pwd) su -c "cd $PWD; bash -l .ci/ci.sh" - travis

transmute_clean_docker:
  stage: clean
  tags:
    - bionicbeaver
    - docker
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - echo clean
