stages:
  - build

transmute_build:
  stage: build
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - bash .ci/linux_before_install.sh
    - bash -l -c "echo PATH=$HOME/.transmute/bin:$PATH >> $HOME/.bashrc"
    - bash -l -c "echo PATH=$HOME/.local/bin:$PATH >> $HOME/.bashrc"
    - bash .ci/ci.sh
