stages:
  - build

transmute_build:
  stage: build
  tags:
    - bionicbeaver
  image: travisci/ci-connie:packer-1512502287-986baf0
  script:
    - bash .ci/linux_before_install.sh
    - su -c "echo PATH=/home/travis/.transmute/bin:$PATH >> /home/travis/.bashrc" - travis
    - su -c "echo PATH=/home/travis/.local/bin:$PATH >> /home/travis/.bashrc" - travis
    - rm -Rf /home/travis/.transmute
    - su -c 'bash -l .ci/ci.sh' - travis
